version: 2

executors:
  docker-executor:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    working_directory: /tmp/thesparktree-blog

jobs:
  build:
    executor: docker-executor
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    steps:
    - checkout
    - run: sudo apt-get --reinstall install libept1.4.12
    - run: sudo apt-get install -y aptitude
    - run: sudo aptitude -y install imagemagick
    - run: sudo aptitude -y install libmagickcore-dev
    - run: sudo aptitude -y install libmagickwand-dev


    # Dependencies
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-src-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-

    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 '
    - run: bundle exec jekyll build --destination ../dist

    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - ~/.bundle
    # Test
    #   This would typically be a build job when using workflows, possibly combined with build
    # This is based on your 1.0 configuration file or project settings
    - run: bundle exec htmlproofer dist --check-html --disable-external --assume-extension

    - persist_to_workspace:
        # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
        # taken to be the root directory of the workspace.
        root: /tmp/thesparktree-blog
        # Must be relative path from root
        paths:
          - dist

  deploy:
    executor: docker-executor
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /tmp/thesparktree-blog
    - deploy:
        name: "Deploy to GH-Pages"
        command: |
          git config --global user.email circleci@circleci
          git config --global user.name CircleCI
          cd dist
          git init
          git checkout master
          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
          git remote add origin git@github.com:AnalogJ/thesparktree-blog.git
          git push --force origin master:master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - src